Lentzi90/add tls support
amimof/node-cert-exporter pull request #69
Opened 2022-02-08 07:42 UTC by lentzi90

Fixes #68 .

**- What I did**
Added TLS support.

**- How I did it**
By adding three new flags (`--tls`, `--tls-cert-file` and `--tls-key-file`).

**- How to verify it**
Generate a server certificate and key:
```bash
openssl genrsa -out server.key 2048
openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
# Fill in some information about the cert as prompted.
# For this example I'm using `node-cert-exporter` as Common Name.
```
Run node-cert-exporter and tell it to use the files:
```bash
node-cert-exporter --tls --tls-key-file=server.key --tls-cert-file=server.crt
```
Use `curl` to check that the connection is encrypted and the correct certificate is used.
```bash
curl --verbose --cacert server.crt --resolve node-cert-exporter:9117:127.0.0.1 https://node-cert-exporter:9117/metrics
# --resolve is used to be able to use the common name as address
# --cacert points to the same certificate that node-cert-exporter is using to verify that it is in fact using the correct key file

# Another option is to add the --insecure flag and just check in the output that the details of the cert are correct
curl --verbose --insecure https://localhost:9117/metrics
```

**- Description for the CHANGELOG**
Added TLS support.

2022-02-15 09:16 UTC, lentzi90 commented
@amimof could you take a look at this please?

2022-02-15 09:33 UTC, amimof commented
Hey, thanks for contributing 👏 I'm actually looking at it at the moment and looks great

2022-02-17 09:17 UTC, kashifest commented
Thanks a lot @lentzi90 for taking care of this. This looks good to me. Any idea @amimof when can we take this PR in?

2022-02-21 07:18 UTC, amimof commented
I've reviewed @lentzi90´s contribution and there are pending changes. Once those are resolved the PR can be merged.

2022-02-21 09:15 UTC, lentzi90 commented
Thanks @amimof ! Do you mean I need to change something in this PR or there is something else that is needed? I'm asking because I don't see any change requests or comments here on the PR. :thinking:

2022-02-21 15:35 UTC, amimof requested changes

2022-02-21 15:37 UTC, amimof commented
> Thanks @amimof ! Do you mean I need to change something in this PR or there is something else that is needed? I'm asking because I don't see any change requests or comments here on the PR. 🤔

My bad. I’ve requested the changes now

2022-02-22 06:45 UTC, lentzi90 commented on cmd/node-cert-exporter/main.go
> +	} else {
Good point! I have updated, please take a look @amimof :slightly_smiling_face:

2022-02-23 14:45 UTC, amimof approved these changes
Looks good 👍

2022-02-23 14:46 UTC, merged